### ISSUE TITLE
SSL Not Working

### ISSUE THREAD

**Issue by barisyild** [ianharrigan/hxWebSockets#29]
I could not run SSL in any way. It says that ssl support is added in the pull request, but ssl does not connect.

**Comment by Gulvan0** [comment]
@ianharrigan Still actual
When the client connects via wss, the server just drops the connection
When the client connects via ws, but upgrades the protocol, it still can't connect and stops attempting to by timeout

**Comment by ianharrigan** [comment]
hmmm, do you have a minimal example (plus server) of it happening? It would make it much easier to diagnose as i dont have a huge amount of time currently 

Cheers,
Ian

**Comment by Gulvan0** [comment]
> hmmm, do you have a minimal example (plus server) of it happening? It would make it much easier to diagnose as i dont have a huge amount of time currently
> 
> Cheers,
> Ian

yes, of course. Just this line of code for client in the main function:

`_ws = new WebSocket("wss://**IP**:**PORT**");`

And this on the server:

`var server = new WebSocketServer<SocketHandler>("**IP**", **PORT**, 100);
server.start();`

With the same SocketHandler as in the example for hashlink.

**Comment by Gulvan0** [comment]
@ianharrigan 
Took a while, but I'm back with the minimal example (see attachment)

Server log:
On client startup:
`INFO  :: Starting server - localhost:5000 (maxConnections: 100)
DEBUG :: ID-1 :: New socket handler
DEBUG :: ID-1 :: Adding to web server handler to list - total: 1
DEBUG :: ID-1 :: Bytes read: 517`
After a minute:
`DEBUG :: ID-1 :: Closed
server/SocketHandler.hx:26: 1. CLOSE
DEBUG :: ID-1 :: Removing web server handler from list - total: 0`

Client console:
On startup:
*silence*
After a minute:
`Test.js:39172 WebSocket connection to 'wss://localhost:5000/' failed: 
open @ Test.js:39172
Test.js:5736 client/Main.hx:27: error
Test.js:5736 client/Main.hx:24: closed`

**Comment by Gulvan0** [comment]
@Tezar sorry for the ping, but could you please give a hint on how to fix the issue described above? Ian Harrigan is quite busy atm and I don't know anything about networking. 

A little advice would be enough for me to start the investigation myself. Thank you in advance.

**Comment by Tezar** [comment]
Hi, no prob. Currently not on PC, but quick try.

Do you need SSL? When you try to set up it on your own server, you actually need to set up your certificates (use them, not generate them) The secure socket [seems to have some API](https://api.haxe.org/sys/ssl/Socket.html) for that. If you are just trying to make Eavesdropping   harder, you can get away with self-generated certificate (and set verifyCert appropriately).

The problem will be the JS running in browser. So far I know, you need user input to allow each connection with "unsecure" (e.g. self-signed) web. Haxe docs even show that secure socket is not available on JS, but without computer, that's as far I can quess.

That being said, I believe that you could setup both ssl and event local devel environment. You would need some existing dummy domain, obtain free certificates from Let's encrypt (or someone similar), and then route your domain to localhost in your host file. Or even use cleartext for development.

But maybe I am all wrong. If the issue is really in the missing certificates, you should see more info on the Network tab of the DevTools - you are using Chrome I presume?

**Comment by Gulvan0** [comment]
> Hi, no prob. Currently not on PC, but quick try.
> 
> Do you need SSL? When you try to set up it on your own server, you actually need to set up your certificates. The secure socket [seems to have some API](https://api.haxe.org/sys/ssl/Socket.html) for that (to use them, not generate them). If you are just trying to make eavesdropping harder, you can get away with self-generated certificate (and set verifyCert appropriately).
> 
> The problem will be the JS running in browser. So far I know, you need user input to allow each connection with "unsecure" (e.g. self-signed) web. Haxe docs even show that secure socket is not available on JS, but without computer, that's as far I can quess.
> 
> That being said, I believe that you could setup both ssl and event local devel environment. You would need some existing dummy domain, obtain free certificates from Let's encrypt (or someone similar), and then route your domain to localhost in your host file. Or even use cleartext for development.
> 
> But maybe I am all wrong. If the issue is really in the missing certificates, you should see more info on the Network tab of the DevTools - you are using Chrome I presume?

I need to create a WSS server using hxwebsockets. There is no problem with a simple WS server, but I can't figure out how to do it to make a server that will interact with clients using the wss protocol.

**Comment by Tezar** [comment]
Ok, so I have reworked the example to be really [minimal.zip](https://github.com/ianharrigan/hxWebSockets/files/6356435/minimal.zip)

The problem is, that server doesn't know that you want to use SSL and opens normal connection. Client side waits for valid SSL handshake and eventually timeouts. You can check this by yourself with changing `wss://` into `ws://` in the client. Server will happily accept it.

The problem lies in this line
https://github.com/ianharrigan/hxWebSockets/blob/0e4c906317e87c4bf0bb5ab99f539af17e0694ab/hx/ws/WebSocketServer.hx#L38
You ned to create SecureSocketImpl instead. I have locally patched constructor to pass secure flag (similar to how ws client handles it internally and you can at least get SSL connection open). But it fails on SSL on verification. Because as I stated before, you need to actually setup your certificates/keys/maybe even trust chains and pass them to the newly created SecureSocketImpl.

I could imagine moving socket creation to own method and creating new subclass `WebSocketSecureServer`. But that requires understanding how to setup SSL server in Haxe in first place. I could put it on my evergrowing todo list or you could pick up the mantle :)

**Comment by Tezar** [comment]
Nice writeup how to setup Haxe SSL https://code.haxe.org/category/other/ssl-socket-server.html

**Comment by Gulvan0** [comment]
> Nice writeup how to setup Haxe SSL https://code.haxe.org/category/other/ssl-socket-server.html

yeah, thanks, already digging into it

**Comment by ianharrigan** [comment]
Hey, really sorry to not be part of the conversation - i had a play a while ago and came to a similar conclusion, ie that you'll need to set up certs to enable proper SSL comms (i got as far as using SecureSocketImpl previously and realizing that wasnt enough), i seem to remember setting up ssl on hxcpp was a pain, but i could be mistaken. 

Either way, thanks guys for working though this (and sorry i could be more help!)

**Comment by Gulvan0** [comment]
> Ok, so I have reworked the example to be really [minimal.zip](https://github.com/ianharrigan/hxWebSockets/files/6356435/minimal.zip)
> 
> The problem is, that server doesn't know that you want to use SSL and opens normal connection. Client side waits for valid SSL handshake and eventually timeouts. You can check this by yourself with changing `wss://` into `ws://` in the client. Server will happily accept it.
> 
> The problem lies in this line
> https://github.com/ianharrigan/hxWebSockets/blob/0e4c906317e87c4bf0bb5ab99f539af17e0694ab/hx/ws/WebSocketServer.hx#L38
> 
> 
> You ned to create SecureSocketImpl instead. I have locally patched constructor to pass secure flag (similar to how ws client handles it internally and you can at least get SSL connection open). But it fails on SSL on verification. Because as I stated before, you need to actually setup your certificates/keys/maybe even trust chains and pass them to the newly created SecureSocketImpl.
> I could imagine moving socket creation to own method and creating new subclass `WebSocketSecureServer`. But that requires understanding how to setup SSL server in Haxe in the first place. I could put it on my evergrowing todo list or you could pick up the mantle :)

Ok, so since I won't need insecure sockets, I edited the start() function of WebSocketServer a bit to use sys.ssl.Socket instead of sys.net.Socket. Now it looks like this:

```
 public function start() {
        _stopServer = false;
        
        _serverSocket = new SecureSocketImpl();
        var cert = Certificate.loadFile('/etc/letsencrypt/live/play-intellector.ru/fullchain.pem');
        _serverSocket.setCA(cert);
        _serverSocket.setCertificate(cert, Key.loadFile('/etc/letsencrypt/live/play-intellector.ru/privkey.pem'));
        _serverSocket.setHostname('play-intellector.ru');
    
        _serverSocket.setBlocking(false);
        _serverSocket.bind(new sys.net.Host(_host), _port);
        _serverSocket.listen(_maxConnections);
        Log.info('Starting server - ${_host}:${_port} (maxConnections: ${_maxConnections})');
        #if cs

        while (true) {
            var continueLoop = tick();
            if (continueLoop == false) {
                break;
            }

            Sys.sleep(sleepAmount);
        }

        #else

        MainLoop.add(function() {
            tick();
            Sys.sleep(sleepAmount);
        });

        #end
}
```
I have also changed the type of the _serverSocket var:
`private var _serverSocket:SecureSocketImpl;`

[WebSocketServer.zip](https://github.com/ianharrigan/hxWebSockets/files/6407798/WebSocketServer.zip)

And now I'm running into the segmentation fault when I try to start the server:
```
INFO  :: Starting server - 185.26.120.165:5000 (maxConnections: 100)
SIGNAL 11
sys.ssl.Socket.accept(C:\HaxeToolkit\haxe\std/hl/_std/sys/ssl/Socket.hx:210)
hx.ws.WebSocketServer_SocketHandler.tick(hx/ws/WebSocketServer.hx:85)
hx.ws.WebSocketServer_SocketHandler.~start.0(hx/ws/WebSocketServer.hx:65)
haxe.$MainLoop.tick(C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:174)
haxe.$EntryPoint.processEvents(C:\HaxeToolkit\haxe\std/haxe/EntryPoint.hx:99)
haxe.$EntryPoint.run(C:\HaxeToolkit\haxe\std/haxe/EntryPoint.hx:135)
fun$768(?:1)
Segmentation fault
```

Can you please give me advice on how to deal with this problem, @Tezar? Seems like some concurrency issue (however, despite changing the line `#if cs` to `#if (cs || hl)`, I ran into this issue nonetheless)

I'm using Debian 9 (stretch) and targeting hl.

**Comment by Gulvan0** [comment]
On the other hand, just using the class from the abovementioned tutorial isn't working either. Despite the successful connection, WebSocket class gets stuck in the "CONNECTING" state forever, so sending messages is impossible.

SecureServer.hx:  [SecureServer.zip](https://github.com/ianharrigan/hxWebSockets/files/6409481/SecureServer.zip)

Server log:
```
src/utils/SecureServer.hx:43: got connection from : {host : sys.net.Host, port : 55202}
src/utils/SecureServer.hx:46: sending socket...
src/utils/SecureServer.hx:48: ok...
src/utils/SecureServer.hx:39: waiting to accept...
src/utils/SecureServer.hx:61: new reader thread...
GET / HTTP/1.1
Host: play-intellector.ru:5000
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Upgrade: websocket
Origin: http://127.0.0.1:3000
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-RU;q=0.8,en;q=0.7,en-US;q=0.6
Sec-WebSocket-Key: mvVrmZ5inhp58iO6xT4CHA==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

**Comment by ianharrigan** [comment]
Hey super sorry for not getting involved! Honestly, i didnt have much to add, i got to the point of using SecureSocketImpl and then didnt get any further! :(

(i guess ill also have to go through that ssl primer for haxe)

**Comment by Gulvan0** [comment]
> Hey super sorry for not getting involved! Honestly, i didnt have much to add, i got to the point of using SecureSocketImpl and then didnt get any further! :(
> 
> (i guess ill also have to go through that ssl primer for haxe)

No, no, it's fine since the amount of work you have with haxeui and other libs.
I think there is some simple thing about managing the websocket server that I still can't get. This should work using the built-in extern WebSocket API and it almost does, but one small yet essential thing doesn't happen so the connection never establishes

**Comment by Tezar** [comment]
So I got SSL working just fine, but there seems to be some interference with buffer handling when SSL handshake already used socket. Fixed onelogical error causing read on empty buffer, so no server doesn't crash anymore. Messages are still not going thru. 

Will investigate, but I am calling it a wrap for tonight. Just wanted to let you know that there is work being done on this.

**Comment by Tezar** [comment]
@Gulvan0 so I pushed potential fixes, you can try them via
`haxelib git hxWebSockets https://github.com/Tezar/hxWebSockets.git`

[Example with self-signed certs](https://github.com/ianharrigan/hxWebSockets/files/6464490/secure.zip)

It runs at least on HL and more extensive testing would be certainly good idea.

When running in browser, you would either need to use certs signed by trusted authority, or add selfsigned certs to your browser truststore.

If everything checks out, will extend docs+PR.

**Comment by ianharrigan** [comment]
Hey Tezar, thanks so much for your effort on this, its hugely appreciated!

**Comment by Gulvan0** [comment]
@Tezar I'll try to test it this week, thank you very much!

**Comment by Gulvan0** [comment]
@Tezar Still getting code 11 Segmentation fault when trying to start a server (Debian)

**Comment by Tezar** [comment]
Intriguing. What version of Debian? Will try to spinup VM.

**Comment by Gulvan0** [comment]
> Intriguing. What version of Debian? Will try to spinup VM.

Debian 9 Stretch. Thanks!

**Comment by Tezar** [comment]
So,
unfortunately couldn't  reproduce :/
![image](https://user-images.githubusercontent.com/659732/118044950-978ccf80-b377-11eb-8e44-5529b198055e.png)

- [ preinstaled image](https://www.linuxvmimages.com/images/debian-9/),
- apt get for haxe (installs old version, but setups paths)
-  manually replaced files with the current Haxe source distribution (not recomended for clean install, since the new files may be not recognized via update system and there may be conflicts, but works for quick&dirty setup)
- normal haxelib setup
- HL git clone + install + `cp /usr/local/lib/libhl.so /lib` + `cp /usr/local/lib/*.hdll /lib`
- `haxelib git hxWebSockets https://github.com/Tezar/hxWebSockets.git`
- example package from https://github.com/ianharrigan/hxWebSockets/issues/29#issuecomment-839557033
- `haxe build.hxml`

```
$uname -v
SMP Debian 4.9.228-1 (2020-07-05)
```
```
$ haxe --version
4.2.1+bf9ff69
```
```
$ hl
HL/JIT 1.12.0 (c)2015-2020 Haxe Foundation
```

Is there any chance, that original library gets picked and not the fixed one? You could try to remove --lib from build.hxml, and manually copy hx directory to client/server dirs just to be sure only things you want gets compiled.

**Comment by Gulvan0** [comment]
@Tezar Thanks! I will try to fix it tomorrow

**Comment by Gulvan0** [comment]
@Tezar 

> manually replaced files with the current Haxe source distribution (not recomended for clean install, since the new files may be not recognized via update system and there may be conflicts, but works for quick&dirty setup)

Could you please explain a bit more about how to do it? My current Haxe version is 3.2.1 since apt-get was the only thing I did.

> HL git clone + install

I've got HL ver. 1.11.0. What should I do to replace it with the newer version? Should I uninstall something and, if yes, how to do it? How to properly install HL from git?

> normal haxelib setup
> haxelib git hxWebSockets https://github.com/Tezar/hxWebSockets.git

I suppose I won't need it as I'm building my app on Windows and then copy the .hl executable to remote using pscp.

**Comment by Tezar** [comment]
@Gulvan0 
oh, well, I am not a linux proficient myself, but let's try it. 

If you are not building on smae system you are runing, we first need to determine which environment is to blame. 
Can you try to run  [this bin.zip](https://github.com/ianharrigan/hxWebSockets/files/6488999/bin.zip) HL? It's compiled from the earlier example.

I am not sure, but I believe that installing just HL on server should be enough. Haxe is not used in runtime.

**Comment by Gulvan0** [comment]
> @Gulvan0
> oh, well, I am not a linux proficient myself, but let's try it.
> 
> If you are not building on smae system you are runing, we first need to determine which environment is to blame.
> Can you try to run [this bin.zip](https://github.com/ianharrigan/hxWebSockets/files/6488999/bin.zip) HL? It's compiled from the earlier example.
> 
> I am not sure, but I believe that installing just HL on server should be enough. Haxe is not used in runtime.

@Tezar This did work, so I think the problem is either with properly connecting to a remote server, or with my code itself. Will investigate further

**Comment by Tezar** [comment]
You can try [this](https://github.com/ianharrigan/hxWebSockets/files/6489064/argsupport.zip). Prebuild in the `bin` dir.

Server now binds to 0.0.0.0 (=all local IP adresses) and client accepts connect string, e.g. 

`hl client.hl "wss://localhost:5000"`

**Comment by Gulvan0** [comment]
> You can try [this](https://github.com/ianharrigan/hxWebSockets/files/6489064/argsupport.zip). Prebuild in the `bin` dir.
> 
> Server now binds to 0.0.0.0 (=all local IP adresses) and client accepts connect string, e.g.
> 
> `hl client.hl "wss://localhost:5000"`

Since that did work too, I think I need to dig into my own code and compare it to yours

**Comment by Gulvan0** [comment]
@Tezar Meanwhile, I've only tested it on hl, why does js only connect to localhost? My server is on hl while my client is on js

**Comment by Tezar** [comment]
@Gulvan0 well, you can connect to anything, but on JS there is no way to pass arguments via cmd line, so it defaults to localhost. You can recompile it with any other value, this was just for demonstration.

**Comment by Gulvan0** [comment]
@Tezar I've tested it on js with my domain and got WebSocket connection to 'wss://host:5000/' failed. I think this is the main problem

**Comment by Gulvan0** [comment]
@Tezar I've tested it on js with my domain name and got WebSocket connection to 'wss://host:5000/' failed. I think this is the main problem

**Comment by Tezar** [comment]
looks like certificate problem, do you have openssl?

`openssl s_client -crlf -connect domain:5000 -servername domain`

it will list certificates chain and possible issues

**Comment by Gulvan0** [comment]
> looks like certificate problem, do you have openssl?
> 
> `openssl s_client -crlf -connect domain:5000 -servername domain`
> 
> it will list certificates chain and possible issues

 Ok, I got it working, will investigate the problem further

**Comment by Gulvan0** [comment]
@Tezar Surprisingly, Haxe 4.1.3 is already outdated. Updating Haxe to the latest version and rebuilding the server solved the problem.

It is time to start a pull request I suppose?

**Comment by Tezar** [comment]
Ok, let's close it that last bug was in the haxe/hl/runtime combination. Not as cathartic resolution, but hey, if it works, it works :) 

Will try to polish PR tomorrow.

**Comment by Tezar** [comment]
@ianharrigan do you want me to bump haxelib version as well?

**Comment by ianharrigan** [comment]
Hey Tezar, thanks soooo much for this, sure - if you want to bump the haxelib version cool - if not dont worry, ill do it when i make a release later today.

Thanks again!

Ian

**Comment by Tezar** [comment]
Thanks for maintaining this Ian!
